service: aws-node-env-variables

frameworkVersion: ">=1.2.0 <3.0.0"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  test:
    handler: handler.test
    environment: ${file(env.yml):${self:provider.stage}}

package:
  exclude:
    - .env.*
