service: aws-node-env-variables

frameworkVersion: ">=1.2.0 <3.0.0"

provider:
  name: aws
  versionFunctions: false
  runtime: nodejs12.x
  profile: default
  stage: ${opt:stage, 'un-dev'}
  environment: ${file(env.yml):${self:provider.stage}}
  region: us-east-1

functions:
  test:
    handler: handler.test

package:
  exclude:
    - .env.*
