version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless@2.25.2
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "yarn.lock" }}
            - dependencies-cache-
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - aws-cli/setup
      - run: yarn build
      - run: yarn get-config
      - run: sls deploy -c serverless.yml -s << parameters.stage >>
workflows:
  pn-deploy:
    jobs:
      - deploy:
          name: deploy_dev
          stage: dev
      - deploy:
          name: deploy_prod
          stage: prod
