version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.2.1
  serverless: circleci/serverless-framework@1.0.1
jobs:
  deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "yarn.lock" }}
            - dependencies-cache-
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: dependencies-cache-{{ checksum "yarn.lock" }}
      - aws-cli/setup
      - serverless/setup
      - run: sls deploy -c serverless.yml -s << parameters.stage >>
workflows:
  pn-deploy:
    jobs:
      - deploy:
          name: deploy_dev
          stage: pn-dev
      - deploy:
          name: deploy_prod
          stage: pn-prod
